apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastinx.fullname" . }}
  labels:
    {{- include "fastinx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "fastinx.selectorLabels" . | nindent 4 }}
